/** AUTH action types */

const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
const CLEAR_AUTH = 'CLEAR_AUTH';
const AUTH_REQUEST = 'AUTH_REQUEST';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';

/** QUESTION action types */

const FETCH_QUESTION_REQUEST = 'FETCH_QUESTION_REQUEST';
const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';

const FETCH_ANSWER_SUCCESS = 'FETCH_ANSWER_SUCCESS';
const FETCH_ANSWER_ERROR = 'FETCH_ANSWER_ERROR';

const UPDATE_QUESTIONS_REQUEST = 'UPDATE_QUESTIONS_REQUEST';
const UPDATE_QUESTIONS_SUCCESS = 'UPDATED_QUESTIONS_SUCCESS';
const UPDATE_QUESTIONS_ERROR = 'UPDATE_QUESTIONS_ERROR';

export {
	SET_AUTH_TOKEN,
	CLEAR_AUTH,
	AUTH_REQUEST,
	AUTH_SUCCESS,
	AUTH_ERROR,

	FETCH_QUESTION_REQUEST,
	FETCH_QUESTION_SUCCESS,
	FETCH_QUESTION_ERROR,

	FETCH_ANSWER_SUCCESS,
	FETCH_ANSWER_ERROR,

	UPDATE_QUESTIONS_ERROR,
	UPDATE_QUESTIONS_SUCCESS,
	UPDATE_QUESTIONS_REQUEST,
};